version: '3.8'

services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: MyFinance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8a5si7y7uxsr88zr8jd3l98m
    ports:
      - "7231:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - myfinance-network

  api:
    build:
      context: ./server/api
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=MyFinance;Username=postgres;Password=8a5si7y7uxsr88zr8jd3l98m"
    volumes:
      - ./server:/app
    networks:
      - myfinance-network

volumes:
  pgdata:

networks:
  myfinance-network:
    driver: bridge
