import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

import { SidebarProvider, SidebarTrigger, Sidebar, SidebarContent } from "@components/ui/sidebar"
import { getLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { loadMessages } from "@lib/loadMessages";

const satoshiFont = localFont({
  src: [
    {
      path: "../public/fonts/Satoshi/OTF/Satoshi-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi/OTF/Satoshi-LightItalic.otf",
      weight: "300",
      style: "italic",
    },
    {
      path: "../public/fonts/Satoshi/OTF/Satoshi-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi/OTF/Satoshi-Italic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/Satoshi/OTF/Satoshi-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi/OTF/Satoshi-MediumItalic.otf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../public/fonts/Satoshi/OTF/Satoshi-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi/OTF/Satoshi-BoldItalic.otf",
      weight: "700",
      style: "italic",
    },
    {
      path: "../public/fonts/Satoshi/OTF/Satoshi-Black.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi/OTF/Satoshi-BlackItalic.otf",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-satoshi", // Used for integration with Tailwind CSS
  display: "swap",
});

export const metadata: Metadata = {
  title: "My Finance",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await loadMessages(locale);

  return (
    <html lang={locale}>
      <body
        className={`${satoshiFont.className} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <SidebarProvider>
            <Sidebar>
              <SidebarContent />
            </Sidebar>
            <main>
              <SidebarTrigger />
              {children}
            </main>
          </SidebarProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
